data_dir: ./data/vklsvd
device: cuda
mode: train_holdout

# outputs
out_dir: "./results/RQ2/vklsvd/rkmeans"

# rkmeans
num_levels: 5 # 5
num_clusters: 4096 # 4096
num_iters: 40
fit_batch_size: 128

# eval
eval_batch_size: 512
per_step: true
expected_holdout_frac: 0.1
